### ISSUE TITLE
修改一下兼容5.4

### ISSUE THREAD

**Issue by y284663247** [crazyfd/yii2-qiniu#1]
把$data['file'] = new \CURLFile($filePath);
修改成：
if (class_exists('\CURLFile')) {
            $data['file'] = new \CURLFile($filePath);
            //$field = array('fieldname' => new \CURLFile(realpath($filepath)));
} else {
            $data['file'] = '@' .$filePath;
            //$field = array('fieldname' => '@' . realpath($filepath));
}
这样5.4就可以用了，我用的是阿里云，没有5.5的，修改了一下

**Comment by crazyfd** [comment]
已经修正，当时做的项目是5.5以上的，就没做5.4版本的

**Comment by y284663247** [comment]
恩，好的
我是在环境上用到5.4，不能切换环境就修改了程序，顺道和你说一下


原始邮件
发件人:crazyfdnotifications@github.com
收件人:crazyfd/yii2-qiniuyii2-qiniu@noreply.github.com
抄送:rickeryulhyfe1987@163.com
发送时间:2015年1月27日(周二) 09:12
主题:Re: [yii2-qiniu] 修改一下兼容5.4 (#1)


已经修正，当时做的项目是5.5以上的，就没做5.4版本的
